[package]
name = "fltk-float"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.4.4"

[features]
fltk-bundled = ["fltk/fltk-bundled"]
static-msvcrt = ["fltk/static-msvcrt"]
